mixed-port: 7890
mode: rule
ipv6: false
geodata-mode: true
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
geo-auto-update: false
geo-update-interval: 24
log-level: info
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
tcp-concurrent: true
find-process-mode: strict
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: false
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
sniffer:
  enable: true
  sniff:
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
dns:
  enable: true
  ipv6: false
  cache-algorithm: arc
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 180.168.255.118
  - 116.228.111.18
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  fallback:
  - tcp://1.1.1.1
  - https://public.dns.iij.jp/dns-query
  - https://doh.pub/dns-query
  nameserver-policy:
    geosite:cn,private:
    - 223.5.5.5
    - 114.114.114.114
proxies:
- name: Sharon-JPstd-Reality
  type: vless
  server: 157.254.198.9
  port: 41455
  uuid: a92e3dc9-4a5d-4575-b193-e5d2ec47b12c
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.lovelive-anime.jp
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: a1Afix542AoiqlUGhFxFkwrFrLTklhB4ve2pSfWSjVI
  client-fingerprint: chrome
- name: V.PS-Tokyo-Reality
  type: vless
  server: 195.245.241.160
  port: 29332
  uuid: 38315afb-f655-454f-9f5b-8f83d1c59730
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.lovelive-anime.jp
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: BN5Uet02yGT83emVXrJQeKkRzKvzwR_OxoLqsVIRhEI
  client-fingerprint: chrome
- name: RN-SJC-Reality
  type: vless
  server: 192.227.148.174
  port: 13769
  uuid: f7540b84-2e58-43ff-8523-0387077a78ef
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: gateway.icloud.com
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: 8g40GLOp70rUWtxanPxXyaN0gbcTnALuz4fXYVXh9xM
  client-fingerprint: chrome
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - Sharon-JPstd-Reality
  - V.PS-Tokyo-Reality
  - RN-SJC-Reality
- name: OpenAI
  type: select
  proxies:
  - Sharon-JPstd-Reality
  - V.PS-Tokyo-Reality
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  steamCN:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml
    path: ./ruleset/steamCN.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.yaml
    path: ./ruleset/GameDownload.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/OpenAI.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/Bing.yaml
    interval: 86400
rules:
- IP-CIDR,10.10.9.9/32,DIRECT
- DOMAIN-SUFFIX,emby.misakaf.org,Proxy
- DOMAIN-SUFFIX,iflow.work,Proxy
- DOMAIN-SUFFIX,hembed.com,OpenAI
- DOMAIN-SUFFIX,hanime1.me,RN-SJC-Reality
- DOMAIN-SUFFIX,chims.co,Proxy
- RULE-SET,GameDownload,DIRECT
- RULE-SET,steamCN,DIRECT
- RULE-SET,OpenAI,OpenAI
- RULE-SET,reject,REJECT
- GEOSITE,category-ads,REJECT
- RULE-SET,gfw,Proxy
- GEOSITE,cn,DIRECT
- GEOIP,cn,DIRECT
- MATCH,Proxy
