mixed-port: 7890
mode: rule
ipv6: false
geodata-mode: true 
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: false # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
log-level: info # 日志等级 silent/error/warning/info/debug
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
tcp-concurrent: true
find-process-mode: strict
unified-delay: true

profile: # 存储 select 选择记录
  store-selected: true
  # 持久化 fake-ip
  store-fake-ip: true

tun:
  enable: false
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

sniffer:
  enable: true
  sniff: # TLS 和 QUIC 默认如果不配置 ports 默认嗅探 443
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    # 默认嗅探 80
    HTTP: # 需要嗅探的端口
      ports: [80, 8080-8880]
      override-destination: true
  sniffing:
    - tls
    - http

dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114

proxies:
  - name: "Sharon-Tokyo-Reality"
    type: vless
    server: 157.254.198.115
    port: 10970
    uuid: 22932a47-a306-4584-baad-63c8c3dec54e
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.lovelive-anime.jp # REALITY servername
    reality-opts:
      short-id: 6ba85179e30d4fc2 # optional
      public-key: 0nIBSBO33PSqQlulcTTKuHOvT1T_TkIxDTnhLECWqwk
    client-fingerprint: chrome # cannot be empty

  - name: "Akile-Tokyo-Reality"
    type: vless
    server: 103.232.213.233
    port: 23416
    uuid: 41f9ae8a-95ac-42ee-938f-7118815ad650
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.lovelive-anime.jp # REALITY servername
    reality-opts:
      public-key: FLvEhDnnFszznZEnoATCbnAxPXhr0DrfgjoTMgPshwo
    client-fingerprint: chrome # cannot be empty
    
  - name: "V.PS-Tokyo-Reality"
    type: vless
    server: 195.245.241.160
    port: 18238
    uuid: d7245ca4-ef8a-4fc1-9ffc-659969dcf6b2
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.lovelive-anime.jp # REALITY servername
    reality-opts:
      short-id: 6ba85179e30d4fc2 # optional
      public-key: MfHz8e-2PAOwH5V87X5oa4NFOY67FL_9iytsRgoKchQ
    client-fingerprint: chrome # cannot be empty

  - name: "RN-SJC-Reality"
    type: vless
    server: 192.227.148.174
    port: 18802
    uuid: f7540b84-2e58-43ff-8523-0387077a78ef
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com # REALITY servername
    reality-opts:
      short-id: 6ba85179e30d4fc2 # optional
      public-key: 8g40GLOp70rUWtxanPxXyaN0gbcTnALuz4fXYVXh9xM
    client-fingerprint: chrome # cannot be empty

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Sharon-Tokyo-Reality
      - Akile-Tokyo-Reality
      - V.PS-Tokyo-Reality
      - RN-SJC-Reality
      
  - name: OpenAI
    type: select
    proxies:
      - Sharon-Tokyo-Reality
      - Akile-Tokyo-Reality
      - V.PS-Tokyo-Reality

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  steamCN:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml"
    path: ./ruleset/steamCN.yaml
    interval: 86400

  GameDownload:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.yaml"
    path: ./ruleset/GameDownload.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/OpenAI.yaml
    interval: 86400


rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - RULE-SET,GameDownload,DIRECT
  - RULE-SET,steamCN,DIRECT
  - DOMAIN-SUFFIX,bing.com,Proxy
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,reject,REJECT
  - GEOSITE,category-ads,REJECT
  - RULE-SET,gfw,Proxy
  - GEOIP,LAN,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,Proxy
