mixed-port: 7890
mode: rule
ipv6: false
geodata-mode: true
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
geo-auto-update: false
geo-update-interval: 24
log-level: info
global-client-fingerprint: chrome
tcp-concurrent: true
find-process-mode: strict
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: false
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
  skip-src-address:
    - 192.168.0.3/32
  skip-dst-address:
    - 192.168.0.3/32
dns:
  enable: true
  respect-rules: false
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
  nameserver-policy:
    '+.arpa': '10.0.0.1'
    'geosite:cn':
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  direct-nameserver:
    - system
  direct-nameserver-follow-policy: false
  fallback-filter:
    geoip: true
    geoip-code: CN
    nameserver-policy:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  
proxies:
- name: Sharon-JPstd-Reality
  type: vless
  server: 157.254.198.9
  port: 41455
  uuid: a92e3dc9-4a5d-4575-b193-e5d2ec47b12c
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.lovelive-anime.jp
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: a1Afix542AoiqlUGhFxFkwrFrLTklhB4ve2pSfWSjVI
  client-fingerprint: chrome
- name: V.PS-Tokyo-Reality
  type: vless
  server: 195.245.241.160
  port: 29332
  uuid: 38315afb-f655-454f-9f5b-8f83d1c59730
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.lovelive-anime.jp
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: BN5Uet02yGT83emVXrJQeKkRzKvzwR_OxoLqsVIRhEI
  client-fingerprint: chrome
- name: RN-SJC-Reality
  type: vless
  server: 107.172.16.17
  port: 18141
  uuid: b8436b8c-27a2-484d-a163-c521a324fbbd
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: gateway.icloud.com
  reality-opts:
    short-id: 6ba85179e30d4fc2
    public-key: q4uI_Vc70vqz-sTsoZwiaZBN5OjiiIfkUn8Gicvr9Tg
  client-fingerprint: chrome
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - Sharon-JPstd-Reality
  - V.PS-Tokyo-Reality
  - RN-SJC-Reality
- name: OpenAI
  type: select
  proxies:
  - Sharon-JPstd-Reality
  - V.PS-Tokyo-Reality
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  steamCN:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml
    path: ./ruleset/steamCN.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.yaml
    path: ./ruleset/GameDownload.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/OpenAI.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/Bing.yaml
    interval: 86400
rules:
- IP-CIDR,10.10.9.9/32,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,emby.misakaf.org,Proxy
- DOMAIN-SUFFIX,terraria.wiki.gg,Proxy
- DOMAIN-SUFFIX,iflow.work,Proxy
- DOMAIN-SUFFIX,hembed.com,OpenAI
- DOMAIN-SUFFIX,hanime1.me,RN-SJC-Reality
- DOMAIN-SUFFIX,chims.co,Proxy
- RULE-SET,GameDownload,DIRECT
- RULE-SET,steamCN,DIRECT
- RULE-SET,OpenAI,OpenAI
- RULE-SET,reject,REJECT
- GEOSITE,category-ads,REJECT
- RULE-SET,gfw,Proxy
- GEOSITE,cn,DIRECT
- GEOIP,cn,DIRECT
- MATCH,Proxy
