mixed-port: 7890
mode: rule
ipv6: false
geodata-mode: true 
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
tcp-concurrent: true
find-process-mode: strict
sniffer:
  enable: true
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
  sniffing:
    - http
    - tls


tun:
  enable: false
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  #inet4-address:
  #  - 28.0.0.1/8
  #inet6-address:
  #  - fdfe:dcba:9876::1/126
  #inet4-route-address:
  #  - 0.0.0.0/1
  #  - 128.0.0.0/1
  #inet6-route-address:
  #  - "::/1"
  #  - "8000::/1"


dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114

proxies:
  - name: "V.PS-Tokyo-Reality"
    type: vless
    server: 195.245.241.160
    port: 35515
    uuid: d7245ca4-ef8a-4fc1-9ffc-659969dcf6b2
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.lovelive-anime.jp # REALITY servername
    reality-opts:
      short-id: 6ba85179e30d4fc2 # optional
      public-key: NbF-AII8hcE4HGmcISyXMyjZThqIHlNB3Fg4KIj9TlU
    client-fingerprint: chrome # cannot be empty
    
  - name: "DMIT-L.A.-Reality"
    type: vless
    server: 154.17.29.173
    port: 16387
    uuid: bc094910-3e76-49c9-b5e8-6a58588e4ab6
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com # REALITY servername
    reality-opts:
      public-key: AHBPN0WhXrUJ8KpQX1Z6mFJVlzAWN4Bb7qhtS0Iucjs
    client-fingerprint: chrome # cannot be empty

  - name: "RN-SJC-Reality"
    type: vless
    server: 192.227.148.174
    port: 18802
    uuid: f7540b84-2e58-43ff-8523-0387077a78ef
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: gateway.icloud.com # REALITY servername
    reality-opts:
      short-id: 6ba85179e30d4fc2 # optional
      public-key: 8g40GLOp70rUWtxanPxXyaN0gbcTnALuz4fXYVXh9xM
    client-fingerprint: chrome # cannot be empty

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - V.PS-Tokyo-Reality
      - DMIT-L.A.-Reality
      - RN-SJC-Reality


rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  steamCN:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml"
    path: ./ruleset/steamCN.yaml
    interval: 86400

  GameDownload:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.yaml"
    path: ./ruleset/GameDownload.yaml
    interval: 86400


rules:
  - RULE-SET,GameDownload,DIRECT
  - RULE-SET,steamCN,DIRECT
  - DOMAIN-SUFFIX,bing.com,Proxy
  - RULE-SET,reject,REJECT
  - GEOSITE,category-ads,REJECT
  - RULE-SET,gfw,Proxy
  - GEOIP,LAN,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,Proxy
